export const activities = [
  {
    slug: "ebike-tours",
    title: "E-bike Tours",
    category: "Adventure",
    price: "Ksh.3,500",
    duration: "3 hours",
    groupSize: "2–8 people",
    image: "https://images.unsplash.com/photo-1528629297340-d1d466945dc5?w=800&q=80",
    description: "Glide through the emerald tea fields and wind along the Tigoni ridgeline on a guided e-bike adventure. No fitness level required — just a sense of adventure.",
    href: "/activities/ebike-tours",
  },
  {
    slug: "farm-tours",
    title: "Farm Tours",
    category: "Tours",
    price: "Ksh.4,500",
    duration: "4 hours",
    groupSize: "2–10 people",
    image: "https://images.unsplash.com/photo-1523741543316-beb7fc7023d8?w=800&q=80",
    description: "Walk through working tea estates, learn the art of picking, and taste freshly processed highland tea at source.",
    href: "/activities/farm-tours",
  },
  {
    slug: "hiking-tours",
    title: "Hiking Tours",
    category: "Adventure",
    price: "Ksh.3,000",
    duration: "4–6 hours",
    groupSize: "2–12 people",
    image: "https://images.unsplash.com/photo-1551632811-561732d1e306?w=800&q=80",
    description: "Trek through indigenous forest, past cascading streams, and up to panoramic escarpment viewpoints with expert local guides.",
    href: "/activities/hiking-tours",
  },
  {
    slug: "custom-experience",
    title: "Custom Experience",
    category: "Bespoke",
    price: "Ksh.3,500",
    duration: "Flexible",
    groupSize: "Any size",
    image: "https://images.unsplash.com/photo-1528605248644-14dd04022da1?w=800&q=80",
    description: "Tell us your dream highland day and we'll craft it — from corporate retreats to romantic anniversaries to family adventures.",
    href: "/activities/custom-experience",
  },
];

export const restaurants = [
  {
    slug: "muna-tree-cafe",
    name: "Muna Tree Café",
    tags: ["CAFÉ", "RESTAURANT"],
    image: "https://images.unsplash.com/photo-1554118811-1e0d58224f24?w=800&q=80",
    href: "/restaurants/muna-tree-cafe",
    description: "A beloved garden café known for its farm-fresh breakfast spreads, wood-fired lunches, and artisan teas. The shaded terrace under the ancient fig tree is a local icon.",
    hours: "7am – 5pm",
    price: "Ksh.1,500 avg",
  },
  {
    slug: "kentmere-club",
    name: "Kentmere Club",
    tags: ["EVENT VENUE", "HORSE RIDING", "HOTEL"],
    image: "https://images.unsplash.com/photo-1414235077428-338989a2e8c0?w=800&q=80",
    href: "/restaurants/kentmere-club",
    description: "A grand colonial estate that's stood since the early 1900s. Fine dining in the original ballroom, equestrian facilities, and sweeping lawns for events of all scales.",
    hours: "8am – 10pm",
    price: "Ksh.3,500 avg",
  },
  {
    slug: "browns-cheese",
    name: "Brown's Cheese Factory",
    tags: ["FARM", "TASTING EXPERIENCE"],
    image: "https://images.unsplash.com/photo-1504674900247-0877df9cc836?w=800&q=80",
    href: "/restaurants/browns-cheese",
    description: "Kenya's most celebrated artisan dairy. Tour the production facility, meet the Jersey herd, and sample an extraordinary range of award-winning highland cheeses and yogurts.",
    hours: "9am – 4pm",
    price: "Ksh.4,000 tasting",
  },
  {
    slug: "tigoni-farm-kitchen",
    name: "Tigoni Farm Kitchen",
    tags: ["FARM-TO-TABLE", "LUNCH", "EVENTS"],
    image: "https://images.unsplash.com/photo-1512621776951-a57141f2eefd?w=800&q=80",
    href: "/restaurants/tigoni-farm-kitchen",
    description: "A weekend pop-up kitchen that transforms fresh highland produce into vibrant seasonal menus. Reservations essential.",
    hours: "Weekends 10am – 3pm",
    price: "Ksh.3,000 menu",
  },
  {
    slug: "limuru-heights",
    name: "Limuru Heights Bar & Grill",
    tags: ["GRILL", "SUNSET VIEWS", "BAR"],
    image: "https://images.unsplash.com/photo-1514933651103-005eec06c04b?w=800&q=80",
    href: "/restaurants/limuru-heights",
    description: "Perched at 2,300m, this open-air grill serves slow-cooked meats and craft cocktails against the most dramatic sunset backdrop in the region.",
    hours: "12pm – 11pm",
    price: "Ksh.2,500 avg",
  },
  {
    slug: "tea-estate-terrace",
    name: "Tea Estate Terrace",
    tags: ["TEA HOUSE", "SCENIC DINING"],
    image: "https://images.unsplash.com/photo-1576092762791-dd9e2220abd1?w=800&q=80",
    href: "/restaurants/tea-estate-terrace",
    description: "Dine in the middle of working tea fields with panoramic views of the Rift Valley escarpment. Afternoon teas and light bites are the specialty.",
    hours: "10am – 6pm",
    price: "Ksh.2,000 avg",
  },
];

export const accommodations = [
  {
    slug: "thayu-house",
    name: "Thayu House, Tigoni",
    tags: ["ACCOMMODATION", "COTTAGES"],
    image: "https://images.unsplash.com/photo-1566073771259-6a8506099945?w=800&q=80",
    href: "/accommodations/thayu-house",
    description: "Traditional stone-and-thatch cottages set in a working farm. Morning mist, birdsong, and fireside evenings make this the quintessential Tigoni stay.",
    priceFrom: "Ksh.8,500/night",
  },
  {
    slug: "siri-mitini",
    name: "Siri Mitini",
    tags: ["ACCOMMODATION", "VACATION HOME", "WINE CELLAR"],
    image: "https://images.unsplash.com/photo-1582719508461-905c673771fd?w=800&q=80",
    href: "/accommodations/siri-mitini",
    description: "A stunning contemporary vacation home with a glass-ceiling lounge, curated wine cellar, and lush private garden. Sleeps 10 — perfect for family getaways.",
    priceFrom: "Ksh.25,000/night",
  },
  {
    slug: "siri",
    name: "Siri",
    tags: ["VACATION RETREAT", "CABIN"],
    image: "https://images.unsplash.com/photo-1501785888041-af3ef285b470?w=800&q=80",
    href: "/accommodations/siri",
    description: "An iconic A-frame cabin rising from the tea fields with 360° highland views. Solar-powered, sustainably built, and breathtakingly beautiful.",
    priceFrom: "Ksh.15,000/night",
  },
  {
    slug: "kentmere-club-hotel",
    name: "Kentmere Club",
    tags: ["HOTEL", "HERITAGE PROPERTY"],
    image: "https://images.unsplash.com/photo-1414235077428-338989a2e8c0?w=800&q=80",
    href: "/accommodations/kentmere-club-hotel",
    description: "Historic colonial hotel with grand suites, sprawling grounds, and access to horse riding, tennis, and fine dining.",
    priceFrom: "Ksh.12,000/night",
  },
];

export const destinations = [
  {
    slug: "serenity-spa",
    name: "Serenity Spa, Tigoni",
    tags: ["SPA", "WELLNESS"],
    image: "https://images.unsplash.com/photo-1540555700478-4be289fbecef?w=800&q=80",
    href: "/destinations/serenity-spa",
    description: "An intimate wellness retreat in a colonial stone manor. Signature massages, highland herbal wraps, and detox programmes set among ancient trees.",
  },
  {
    slug: "limuru-country-club",
    name: "Limuru Country Club",
    tags: ["GOLF", "LEISURE"],
    image: "https://images.unsplash.com/photo-1587174486073-ae5e5cff23aa?w=800&q=80",
    href: "/destinations/limuru-country-club",
    description: "One of Kenya's most scenic golf courses, perched on the edge of the Rift Valley escarpment with sweeping views across the Great Rift.",
  },
  {
    slug: "twin-rivers",
    name: "Twin Rivers, Tigoni",
    tags: ["OUTDOORS", "PICNIC"],
    image: "https://images.unsplash.com/photo-1433086966358-54859d0ed716?w=800&q=80",
    href: "/destinations/twin-rivers",
    description: "Where two highland streams converge in a forested valley, this natural picnic ground and ATV trail is perfect for families and adventure groups.",
  },
  {
    slug: "tigoni-dam",
    name: "Tigoni Dam",
    tags: ["FISHING", "BIRDWATCHING"],
    image: "https://images.unsplash.com/photo-1469122312224-c5846569feb1?w=800&q=80",
    href: "/destinations/tigoni-dam",
    description: "A tranquil reservoir surrounded by acacia woodland. Bring a fishing rod, binoculars, and a picnic basket for a full day of highland serenity.",
  },
  {
    slug: "aberdare-viewpoint",
    name: "Aberdare Viewpoint",
    tags: ["SCENIC", "PHOTOGRAPHY"],
    image: "https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=800&q=80",
    href: "/destinations/aberdare-viewpoint",
    description: "The best panoramic view in the region. On a clear morning, you can see Mt Kenya to the north and the Rift Valley to the west simultaneously.",
  },
  {
    slug: "tigoni-forest",
    name: "Tigoni Forest Reserve",
    tags: ["NATURE", "FOREST WALK"],
    image: "https://images.unsplash.com/photo-1448375240586-882707db888b?w=800&q=80",
    href: "/destinations/tigoni-forest",
    description: "A protected strip of indigenous highland forest with self-guided trails, endemic plant species, and spectacular highland birding.",
  },
];
